stages:
  data_ingestion:
    cmd: python src/pipeline/stage_01_data_ingest_pipe.py
    deps:
      - src/pipeline/stage_01_data_ingest_pipe.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/AmesHousing.csv
      - artifacts/data_ingestion/test.csv
      - artifacts/data_ingestion/train.csv

  data_transformation:
    cmd: python src/pipeline/stage_02_data_transform.py
    deps:
      - src/pipeline/stage_02_data_transform.py
      - config/config.yaml
    outs:
      - artifacts/data_transformation/final_test.csv
      - artifacts/data_transformation/final_train.csv
      - artifacts/data_transformation/preprocessor.pkl

  model_trainer:
    cmd: python src/pipeline/stage_03_model_trainer.py
    deps:
      - config/config.yaml
      - artifacts/data_transformation/final_test.csv
      - artifacts/data_transformation/final_train.csv
      - src/pipeline/stage_03_model_Trainer.py
    params:
      - RandomForestRegressor.n_estimators
      - RandomForestRegressor.max_depth
      - RandomForestRegressor.min_samples_split
      - RandomForestRegressor.min_samples_leaf
      - RandomForestRegressor.max_features
      - RandomForestRegressor.criterion
    outs:
      - artifacts/model_trainer/model.pkl

  model_evaluation:
    cmd: python src/pipeline/stage_04_model_evaluation.py
    deps:
      - src/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_transformation/final_test.csv
      - artifacts/model_trainer/model.pkl
    metrics:
      - scores.json:
          cache: false