RandomForestRegressor:
  n_estimators: [100, 200, 300]
  max_depth: [10, 20, 30, None]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]
  max_features: ['auto', 'sqrt', 'log2']
  criterion: ['squared_error', 'absolute_error', 'friedman_mse']
